#!/usr/bin/env python3
"""
ReleaseCaptain Push Packet Generator — V5 GitHub Publication Lane

Generates a structured push packet for ReleaseCaptain authorization.
The command firewall blocks automated push; this packet provides
all information needed for a human ReleaseCaptain to execute.
"""

import json
import subprocess
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import List, Optional


@dataclass
class ReleaseCaptainPushPacket:
    """Canonical push packet for ReleaseCaptain review and execution."""
    
    # Identity
    packet_id: str = field(default_factory=lambda: datetime.now().strftime("%Y%m%d_%H%M%S"))
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    generator: str = "roxy-gtk-v5-release-captain-packet"
    
    # Repository
    repo_path: str = "/mnt/work/roxy-core/apps/roxy-command-center-review"
    repo_name: str = "roxy-command-center"
    remote_name: str = "origin"
    remote_url: str = "https://github.com/markvandendool/roxy-command-center.git"
    
    # Commit
    commit_hash: str = ""
    commit_short: str = ""
    commit_message: str = ""
    commit_author: str = ""
    commit_date: str = ""
    
    # Branch
    branch: str = "main"
    
    # Files changed
    changed_files: List[str] = field(default_factory=list)
    insertions: int = 0
    deletions: int = 0
    
    # Push command
    push_command: str = ""
    
    # Verification
    pre_push_verification: List[str] = field(default_factory=list)
    post_push_verification: List[str] = field(default_factory=list)
    
    # Authority
    requested_by: str = "Regent-Command-ROXY-GTK-V5"
    reason: str = "V5 Agent Operating Console production delivery"
    risk_level: str = "low"
    rollback_commit: str = ""
    
    def to_dict(self) -> dict:
        return asdict(self)
    
    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, default=str)
    
    def to_markdown(self) -> str:
        lines = [
            "# ReleaseCaptain Push Packet",
            f"**Packet ID:** `{self.packet_id}`",
            f"**Generated:** {self.generated_at}",
            f"**Requested by:** {self.requested_by}",
            f"**Reason:** {self.reason}",
            "",
            "## Repository",
            f"- **Path:** `{self.repo_path}`",
            f"- **Name:** {self.repo_name}",
            f"- **Remote:** `{self.remote_name}` → `{self.remote_url}`",
            "",
            "## Commit",
            f"- **Hash:** `{self.commit_hash}`",
            f"- **Short:** `{self.commit_short}`",
            f"- **Message:** {self.commit_message}",
            f"- **Author:** {self.commit_author}",
            f"- **Date:** {self.commit_date}",
            f"- **Branch:** `{self.branch}`",
            "",
            "## Changes",
            f"- **Files:** {len(self.changed_files)}",
            f"- **Insertions:** +{self.insertions}",
            f"- **Deletions:** -{self.deletions}",
            "",
            "### Changed files",
        ]
        for f in self.changed_files:
            lines.append(f"- `{f}`")
        
        lines.extend([
            "",
            "## Push Command",
            f"```bash",
            f"cd {self.repo_path}",
            f"{self.push_command}",
            f"```",
            "",
            "## Pre-Push Verification",
        ])
        for v in self.pre_push_verification:
            lines.append(f"- [ ] {v}")
        
        lines.extend([
            "",
            "## Post-Push Verification",
        ])
        for v in self.post_push_verification:
            lines.append(f"- [ ] {v}")
        
        lines.extend([
            "",
            "## Rollback",
            f"- **Rollback commit:** `{self.rollback_commit}`",
            f"```bash",
            f"cd {self.repo_path}",
            f"git push {self.remote_name} {self.rollback_commit}:{self.branch} --force-with-lease",
            f"```",
            "",
            "## Authority",
            f"- **Risk level:** {self.risk_level}",
            f"- **ReleaseCaptain approval required:** YES",
            "",
            "---",
            "*This packet was generated by the Roxy GTK Command Center V5 Agent Operating Console.*",
        ])
        return "\n".join(lines)


def generate_packet(repo_path: str = "/mnt/work/roxy-core/apps/roxy-command-center-review") -> ReleaseCaptainPushPacket:
    """Generate a push packet from the current state of the repo."""
    packet = ReleaseCaptainPushPacket(repo_path=repo_path)
    
    # Read commit info
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo_path, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            packet.commit_hash = result.stdout.strip()
            packet.commit_short = packet.commit_hash[:12]
        
        result = subprocess.run(
            ["git", "log", "-1", "--format=%H|%an|%ae|%ad|%s"],
            cwd=repo_path, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            parts = result.stdout.strip().split("|", 4)
            if len(parts) >= 5:
                packet.commit_hash = parts[0]
                packet.commit_short = parts[0][:12]
                packet.commit_author = f"{parts[1]} <{parts[2]}>"
                packet.commit_date = parts[3]
                packet.commit_message = parts[4]
        
        result = subprocess.run(
            ["git", "diff", "--stat", "HEAD~1..HEAD"],
            cwd=repo_path, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            lines = result.stdout.strip().split("\n")
            if lines:
                # Parse "N files changed, N insertions(+), N deletions(-)"
                last_line = lines[-1]
                if "files changed" in last_line or "file changed" in last_line:
                    parts = last_line.split(",")
                    for part in parts:
                        if "insertion" in part:
                            packet.insertions = int(''.join(c for c in part if c.isdigit()) or 0)
                        elif "deletion" in part:
                            packet.deletions = int(''.join(c for c in part if c.isdigit()) or 0)
                    # File list (everything before the summary line)
                    packet.changed_files = [l.strip().split("|")[0].strip() for l in lines[:-1] if l.strip() and "Bin" not in l]
                else:
                    # No summary line, all lines are files
                    packet.changed_files = [l.strip().split("|")[0].strip() for l in lines if l.strip()]
        
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=repo_path, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            packet.branch = result.stdout.strip()
        
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_path, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            packet.remote_url = result.stdout.strip()
        
        # Rollback commit (parent of current)
        result = subprocess.run(
            ["git", "rev-parse", "HEAD~1"],
            cwd=repo_path, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            packet.rollback_commit = result.stdout.strip()[:12]
        
    except Exception as e:
        print(f"[ReleaseCaptain] Error reading git state: {e}")
    
    # Build push command
    packet.push_command = f"git push {packet.remote_name} {packet.branch}"
    
    # Verification steps
    packet.pre_push_verification = [
        f"Verify commit {packet.commit_short} is the intended HEAD",
        f"Review changed files ({len(packet.changed_files)} files)",
        "Run local tests if applicable",
        "Verify no secrets in diff",
    ]
    
    packet.post_push_verification = [
        f"Verify remote HEAD matches {packet.commit_short}",
        f"Check {packet.remote_url}/commits/{packet.branch}",
        "Verify CI passes (if enabled)",
    ]
    
    return packet


def save_packet(packet: ReleaseCaptainPushPacket, output_dir: Optional[Path] = None) -> Path:
    """Save packet to JSON and Markdown files."""
    if output_dir is None:
        output_dir = Path.home() / ".config" / "roxy-command-center" / "exports"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    base_name = f"release-captain-push-{packet.packet_id}"
    
    json_path = output_dir / f"{base_name}.json"
    json_path.write_text(packet.to_json())
    
    md_path = output_dir / f"{base_name}.md"
    md_path.write_text(packet.to_markdown())
    
    return json_path, md_path


if __name__ == "__main__":
    packet = generate_packet()
    json_path, md_path = save_packet(packet)
    
    print("=" * 60)
    print("RELEASE CAPTAIN PUSH PACKET")
    print("=" * 60)
    print(f"\nCommit: {packet.commit_short}")
    print(f"Message: {packet.commit_message}")
    print(f"Files: {len(packet.changed_files)} (+{packet.insertions}/-{packet.deletions})")
    print(f"\nPush command:")
    print(f"  cd {packet.repo_path}")
    print(f"  {packet.push_command}")
    print(f"\nSaved:")
    print(f"  JSON: {json_path}")
    print(f"  Markdown: {md_path}")
    print("\n" + packet.to_markdown())
